name: build  # This name is shown on the badge
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: do-the-tests
        run: |
          cmake -S . -B build_TMP
          cmake --build build_TMP --target check

